### ISSUE TITLE
Better error messages when parsing HRDF

### ISSUE THREAD

**Issue by daverolli** [HebiRobotics/hebi-matlab-api#35]
Right the error messages when there's a typo in an HRDF aren't very useful.  You usually just get: 
`input file is not a valid hrdf file:  null`.

Any sort of hit as to even what line the parsing failed would help a ton.

**Comment by ennerf** [comment]
It seems there was a required attribute that didn't get validated (case 4). I've added a generic validation scheme so that won't happen in the future. The various error cases are currently (next snapshot) implemented as below. Let me know if you think I forgot anything.


###  **unknown element** (e.g. `link2`)

`unexpected element (uri:"", local:"link2"). Expected elements are <{}actuator>,<{}joint>,<{}overrideableElement>,<{}end-effector>,<{}bracket>,<{}link>,<{}rigid-body>`

### **unknown attribute** (e.g. `<link ... unknown_attribute="3"/>`

seems to get silently ignored. Not sure how to get access to that :(

### **bad attribute value** (e.g. `type="X5-3"` or `extension="pretty long"`)

* enum: `Unknown value: X5-3`
* number: `Invalid floating point number: 'pretty long'. Expected number or formula`

### **missing required attribute** (e.g. `type2="X5"`)

current:
`NullPointerException`

changed to:
`Missing required attribute: "type"`

### **missing xml (end) tags** (e.g. `<link type="X5-1"`)

`org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 3; The element type "link" must be terminated by the matching end-tag "</link>`
